### python3のバージョンを確認

In [5]:
!which python3

/usr/bin/python3

### cif2POSCAR

In [7]:
# from pymatgen.io.cif import CifParser
# from pymatgen.io.vasp.inputs import Poscar

# # CIFファイルのパスを指定
# cif_file = "1010928.cif"

# # CIFファイルを読み込む
# cif_parser = CifParser(cif_file)
# structure = cif_parser.get_structures()[0]

# # POSCARファイルに変換
# poscar = Poscar(structure)

# # POSCARファイルを保存
# poscar.write_file("POSCAR")

# print("POSCARファイルが作成されました: POSCAR")

### packageからVESTAを読みだす

In [8]:
from my_package import visualize

### ASEでPOSCARファイルを可視化

In [40]:
from ase.io import read, write
# POSCARファイルの読み込み
atoms = read('POSCAR')

# POSCARファイルの描画
from ase.visualize import view, ngl
ngl.view_ngl(atoms)

FileNotFoundError: [Errno 2] No such file or directory: 'POSCAR'

### Converting a POSCAR file to a DataFrame

In [10]:
from my_package.textfile2df import poscar2df_coords 

df_coords = poscar2df_coords(filename='./POSCAR')
df_coords

,central atom,x,y,z,Species
0,1,0.000000000000000,0.764000000000000,0.153000000000000,C
1,2,0.500000000000000,0.736000000000000,0.653000000000000,C
2,3,0.000000000000000,0.236000000000000,0.847000000000000,C
3,4,0.500000000000000,0.764000000000000,0.153000000000000,C
4,5,0.000000000000000,0.736000000000000,0.653000000000000,C
5,6,0.500000000000000,0.264000000000000,0.347000000000000,C
6,7,0.500000000000000,0.236000000000000,0.847000000000000,C
7,8,0.000000000000000,0.264000000000000,0.347000000000000,C
8,9,0.000000000000000,0.417000000000000,0.000000000000000,Pb
9,10,0.500000000000000,0.083000000000000,0.500000000000000,Pb
10,11,0.000000000000000,0.583000000000000,0.000000000000000,Pb
11,12,0.500000000000000,0.417000000000000,0.000000000000000,Pb
12,13,0.000000000000000,0.083000000000000,0.500000000000000,Pb
13,14,0.500000000000000,0.917000000000000,0.500000000000000,Pb
14,15,0.500000000000000,0.583000000000000,0.000000000000000,Pb
15,16,0.000000000000000,0.917000000000000,0.500000000000000,Pb
16,17,0.000000000000000,0.909000000000000,0.153000000000000,O
17,18,0.500000000000000,0.591000000000000,0.653000000000000,O
18,19,0.000000000000000,0.091000000000000,0.847000000000000,O
19,20,0.500000000000000,0.909000000000000,0.153000000000000,O
20,21,0.000000000000000,0.591000000000000,0.653000000000000,O
21,22,0.500000000000000,0.409000000000000,0.347000000000000,O
22,23,0.500000000000000,0.091000000000000,0.847000000000000,O
23,24,0.000000000000000,0.409000000000000,0.347000000000000,O
24,25,0.199000000000000,0.691000000000000,0.153000000000000,O
25,26,0.301000000000000,0.809000000000000,0.653000000000000,O
26,27,0.801000000000000,0.309000000000000,0.847000000000000,O
27,28,0.301000000000000,0.691000000000000,0.153000000000000,O
28,29,0.199000000000000,0.809000000000000,0.653000000000000,O
29,30,0.699000000000000,0.191000000000000,0.347000000000000,O
30,31,0.699000000000000,0.309000000000000,0.847000000000000,O
31,32,0.801000000000000,0.191000000000000,0.347000000000000,O

### converting POSCAR.nnlist to df_nnlist

In [11]:
from my_package.textfile2df import nnlist2df
import pandas as pd

#行の表示数の上限を撤廃
pd.set_option('display.max_rows', None)

df_nnlist = nnlist2df(POSCAR_nnlist='POSCAR.nnlist')
df_nnlist

,central atom,neighboring atom,distance,X,Y,Z,unitcell_x,unitcell_y,unitcell_z,central species,neighboring species
0,1,1,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
1,1,11,1.798174,0.000000,-1.532708,-0.940338,0,0,0,C,Pb
2,1,17,1.227860,0.000000,1.227860,0.000000,0,0,0,C,O
3,1,25,1.199575,1.028034,-0.618164,0.000000,0,0,0,C,O
4,1,28,1.673334,1.554966,-0.618164,0.000000,0,0,0,C,O
5,2,2,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
6,2,14,1.798174,0.000000,1.532708,-0.940338,0,0,0,C,Pb
7,2,18,1.227860,0.000000,-1.227860,0.000000,0,0,0,C,O
8,2,26,1.199575,-1.028034,0.618164,0.000000,0,0,0,C,O
9,2,29,1.673334,-1.554966,0.618164,0.000000,0,0,0,C,O
10,3,3,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
11,3,9,1.798174,0.000000,1.532708,0.940338,0,0,1,C,Pb
12,3,19,1.227860,0.000000,-1.227860,0.000000,0,0,0,C,O
13,3,27,1.199575,-1.028034,0.618164,0.000000,-1,0,0,C,O
14,3,31,1.673334,-1.554966,0.618164,0.000000,-1,0,0,C,O
15,4,4,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
16,4,15,1.798174,0.000000,-1.532708,-0.940338,0,0,0,C,Pb
17,4,20,1.227860,0.000000,1.227860,0.000000,0,0,0,C,O
18,4,25,1.673334,-1.554966,-0.618164,0.000000,0,0,0,C,O
19,4,28,1.199575,-1.028034,-0.618164,0.000000,0,0,0,C,O
20,5,5,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
21,5,16,1.798174,0.000000,1.532708,-0.940338,0,0,0,C,Pb
22,5,21,1.227860,0.000000,-1.227860,0.000000,0,0,0,C,O
23,5,26,1.673334,1.554966,0.618164,0.000000,0,0,0,C,O
24,5,29,1.199575,1.028034,0.618164,0.000000,0,0,0,C,O
25,6,6,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
26,6,10,1.798174,0.000000,-1.532708,0.940338,0,0,0,C,Pb
27,6,22,1.227860,0.000000,1.227860,0.000000,0,0,0,C,O
28,6,30,1.199575,1.028034,-0.618164,0.000000,0,0,0,C,O
29,6,32,1.673334,1.554966,-0.618164,0.000000,0,0,0,C,O
30,7,7,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
31,7,12,1.798174,0.000000,1.532708,0.940338,0,0,1,C,Pb
32,7,23,1.227860,0.000000,-1.227860,0.000000,0,0,0,C,O
33,7,27,1.673334,1.554966,0.618164,0.000000,0,0,0,C,O
34,7,31,1.199575,1.028034,0.618164,0.000000,0,0,0,C,O
35,8,8,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
36,8,13,1.798174,0.000000,-1.532708,0.940338,0,0,0,C,Pb
37,8,24,1.227860,0.000000,1.227860,0.000000,0,0,0,C,O
38,8,30,1.673334,-1.554966,-0.618164,0.000000,-1,0,0,C,O
39,8,32,1.199575,-1.028034,-0.618164,0.000000,-1,0,0,C,O
40,9,3,1.798174,0.000000,-1.532708,-0.940338,0,0,-1,Pb,C
41,9,9,0.000000,0.000000,0.000000,0.000000,0,0,0,Pb,Pb
42,9,11,1.405688,0.000000,1.405688,0.000000,0,0,0,Pb,Pb
43,9,27,1.666577,-1.028034,-0.914544,-0.940338,-1,0,-1,Pb,O
44,10,6,1.798174,0.000000,1.532708,-0.940338,0,0,0,Pb,C
45,10,10,0.000000,0.000000,0.000000,0.000000,0,0,0,Pb,Pb
46,10,14,1.405688,0.000000,-1.405688,0.000000,0,-1,0,Pb,Pb
47,10,30,1.666577,1.028034,0.914544,-0.940338,0,0,0,Pb,O
48,11,1,1.798174,0.000000,1.532708,0.940338,0,0,0,Pb,C
49,11,9,1.405688,0.000000,-1.405688,0.000000,0,0,0,Pb,Pb
50,11,11,0.000000,0.000000,0.000000,0.000000,0,0,0,Pb,Pb
51,11,25,1.666577,1.028034,0.914544,0.940338,0,0,0,Pb,O
52,12,7,1.798174,0.000000,-1.532708,-0.940338,0,0,-1,Pb,C
53,12,12,0.000000,0.000000,0.000000,0.000000,0,0,0,Pb,Pb
54,12,15,1.405688,0.000000,1.405688,0.000000,0,0,0,Pb,Pb
55,12,31,1.666577,1.028034,-0.914544,-0.940338,0,0,-1,Pb,O
56,13,8,1.798174,0.000000,1.532708,-0.940338,0,0,0,Pb,C
57,13,13,0.000000,0.000000,0.000000,0.000000,0,0,0,Pb,Pb
58,13,16,1.405688,0.000000,-1.405688,0.000000,0,-1,0,Pb,Pb
59,13,32,1.666577,-1.028034,0.914544,-0.940338,-1,0,0,Pb,O
60,14,2,1.798174,0.000000,-1.532708,0.940338,0,0,0,Pb,C
61,14,10,1.405688,0.000000,1.405688,0.000000,0,1,0,Pb,Pb
62,14,14,0.000000,0.000000,0.000000,0.000000,0,0,0,Pb,Pb
63,14,26,1.666577,-1.028034,-0.914544,0.940338,0,0,0,Pb,O
64,15,4,1.798174,0.000000,1.532708,0.940338,0,0,0,Pb,C
65,15,12,1.405688,0.000000,-1.405688,0.000000,0,0,0,Pb,Pb
66,15,15,0.000000,0.000000,0.000000,0.000000,0,0,0,Pb,Pb
67,15,28,1.666577,-1.028034,0.914544,0.940338,0,0,0,Pb,O
68,16,5,1.798174,0.000000,-1.532708,0.940338,0,0,0,Pb,C
69,16,13,1.405688,0.000000,1.405688,0.000000,0,1,0,Pb,Pb
70,16,16,0.000000,0.000000,0.000000,0.000000,0,0,0,Pb,Pb
71,16,29,1.666577,1.028034,-0.914544,0.940338,0,0,0,Pb,O
72,17,1,1.227860,0.000000,-1.227860,0.000000,0,0,0,O,C
73,17,17,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
74,18,2,1.227860,0.000000,1.227860,0.000000,0,0,0,O,C
75,18,18,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
76,19,3,1.227860,0.000000,1.227860,0.000000,0,0,0,O,C
77,19,19,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
78,20,4,1.227860,0.000000,-1.227860,0.000000,0,0,0,O,C
79,20,20,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
80,21,5,1.227860,0.000000,1.227860,0.000000,0,0,0,O,C
81,21,21,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
82,22,6,1.227860,0.000000,-1.227860,0.000000,0,0,0,O,C
83,22,22,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
84,23,7,1.227860,0.000000,1.227860,0.000000,0,0,0,O,C
85,23,23,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
86,24,8,1.227860,0.000000,-1.227860,0.000000,0,0,0,O,C
87,24,24,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
88,25,1,1.199575,-1.028034,0.618164,0.000000,0,0,0,O,C
89,25,4,1.673334,1.554966,0.618164,0.000000,0,0,0,O,C
90,25,11,1.666577,-1.028034,-0.914544,-0.940338,0,0,0,O,Pb
91,25,25,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
92,25,28,0.526932,0.526932,0.000000,0.000000,0,0,0,O,O
93,26,2,1.199575,1.028034,-0.618164,0.000000,0,0,0,O,C
94,26,5,1.673334,-1.554966,-0.618164,0.000000,0,0,0,O,C
95,26,14,1.666577,1.028034,0.914544,-0.940338,0,0,0,O,Pb
96,26,26,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
97,26,29,0.526932,-0.526932,0.000000,0.000000,0,0,0,O,O
98,27,3,1.199575,1.028034,-0.618164,0.000000,1,0,0,O,C
99,27,7,1.673334,-1.554966,-0.618164,0.000000,0,0,0,O,C
100,27,9,1.666577,1.028034,0.914544,0.940338,1,0,1,O,Pb
101,27,27,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
102,27,31,0.526932,-0.526932,0.000000,0.000000,0,0,0,O,O
103,28,1,1.673334,-1.554966,0.618164,0.000000,0,0,0,O,C
104,28,4,1.199575,1.028034,0.618164,0.000000,0,0,0,O,C
105,28,15,1.666577,1.028034,-0.914544,-0.940338,0,0,0,O,Pb
106,28,25,0.526932,-0.526932,0.000000,0.000000,0,0,0,O,O
107,28,28,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
108,29,2,1.673334,1.554966,-0.618164,0.000000,0,0,0,O,C
109,29,5,1.199575,-1.028034,-0.618164,0.000000,0,0,0,O,C
110,29,16,1.666577,-1.028034,0.914544,-0.940338,0,0,0,O,Pb
111,29,26,0.526932,0.526932,0.000000,0.000000,0,0,0,O,O
112,29,29,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
113,30,6,1.199575,-1.028034,0.618164,0.000000,0,0,0,O,C
114,30,8,1.673334,1.554966,0.618164,0.000000,1,0,0,O,C
115,30,10,1.666577,-1.028034,-0.914544,0.940338,0,0,0,O,Pb
116,30,30,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
117,30,32,0.526932,0.526932,0.000000,0.000000,0,0,0,O,O
118,31,3,1.673334,1.554966,-0.618164,0.000000,1,0,0,O,C
119,31,7,1.199575,-1.028034,-0.618164,0.000000,0,0,0,O,C
120,31,12,1.666577,-1.028034,0.914544,0.940338,0,0,1,O,Pb
121,31,27,0.526932,0.526932,0.000000,0.000000,0,0,0,O,O
122,31,31,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
123,32,6,1.673334,-1.554966,0.618164,0.000000,0,0,0,O,C
124,32,8,1.199575,1.028034,0.618164,0.000000,1,0,0,O,C
125,32,13,1.666577,1.028034,-0.914544,0.940338,1,0,0,O,Pb
126,32,30,0.526932,-0.526932,0.000000,0.000000,0,0,0,O,O
127,32,32,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O

#### df_nnlist.groupby('central atom').count()['neighboring atom']で最も要素数の多いもののcentral atomをクラスタとして得る．
#### → クラスタ化されたcentral atomを重複削除する　
#### → 新しいcentral atomのリストを得る

In [12]:
print(df_nnlist.groupby('central atom').count()['neighboring atom'])
# これをフィルター化したものがget_elelem_max_num_filter_list

central atom
1     5
2     5
3     5
4     5
5     5
6     5
7     5
8     5
9     4
10    4
11    4
12    4
13    4
14    4
15    4
16    4
17    2
18    2
19    2
20    2
21    2
22    2
23    2
24    2
25    5
26    5
27    5
28    5
29    5
30    5
31    5
32    5
Name: neighboring atom, dtype: int64

#### df_nnlist.groupby('central atom').count()['neighboring atom']で最も要素数の多いもののcentral atomをクラスタとして得る．

In [13]:
def get_elem_max_filter(df_nnlist=df_nnlist):
    """
    To get cluster center abs coords from df_coords, Please use this filter.
    
    Input: df_nnlist 
 -> Output: The max number of element 
            in neighboring column of df_nnlist, 
            when df_nnlist groupbyed neighboring column and .count() 
    
    param1: df_nnlist: It should be created by nnlist2df()
    """
    
    elem_max_num = df_nnlist.groupby('central atom').count()['neighboring atom'].max()
    elem_max_num_filter = df_nnlist.groupby('central atom').count()['neighboring atom'] == elem_max_num
    elem_max_num_filter_list = elem_max_num_filter.to_list()
    return elem_max_num_filter_list

#### メモ：df_coords[elem_max_num_filter_list] によりクラスタ中心の絶対座標を得る

In [14]:
# df_coords[elem_max_num_filter_list]

#### df_nnlistで入力：central atom → 出力：neighboring atom を返す関数get_right_valueを作成．

In [15]:
import pandas as pd

# 入力値が左側の数値と同じ場合、対応する右側の数値を返す関数
def get_right_value(input_value):
    """
    To get all central atoms of a cluster(:neighbors), Input a number of cluster center element number(:central atom)
    
    Input: central atom column element In df_nnlist
 -> Output: All neighboring atom column element that Input(:elemnt) match central atom column element
    
    param1: Input: central atom column element In df_nnlist
    """
    
    # 左側の列から対応する行を選択し、右側の数値を取得
    # result = df_nnlist[df_nnlist['central atom'] == input_value]['neighboring atom'].values
    result = df_nnlist[df_nnlist['central atom'] == input_value]['neighboring atom'].tolist()
    return result

# 関数をテスト
get_right_value(1)

[1, 11, 17, 25, 28]

#### クラスタ中心のcentral atom(id的な番号)の一覧を得る

### クラスタに選ばれなかった残りのcentral atom (≒id)の一覧を得る関数

In [16]:
def get_all_non_cluster_atom(df_nnlist=df_nnlist, df_coords=df_coords):
    """
    dependency: get_elem_max_filter(), get_right_value()
    
    To get non-clusterd central atom list, Use this func.
    
    
    Input: DataFrames
 -> Output: a list 
    
    param1: df_nnlist=df_nnlist
    param2: df_coords=df_coords
    """
    elem_max_num_filter_list = get_elem_max_filter(df_nnlist=df_nnlist)
    cluster_central_atom_list = df_coords[elem_max_num_filter_list]['central atom'].tolist()
    cluster_all_atom_list_dubled = [get_right_value(elem) for elem in cluster_central_atom_list]
    # 2重リストを1重リストにflated
    flat_list = [item for sublist in cluster_all_atom_list_dubled for item in sublist]
    # flat_listの重複削除
    cluster_all_atom_set = set(flat_list)
    
    # ここからdf_coordsを使う
    all_central_atom_set = set(df_coords['central atom'].tolist())
    
    # 差分を取得
    diff_central_atom_list = list(all_central_atom_set.difference(cluster_all_atom_set))
    
    return diff_central_atom_list

In [17]:
get_all_non_cluster_atom(df_nnlist=df_nnlist, df_coords=df_coords)

[]

### diff_central_atom_listをフィルター化する関数

In [18]:
# diff_central_atom_filter = df_coords['central atom'].apply(lambda row: row in diff_central_atom_list)
# これをget_diff_central_atom_filterに関数化

In [19]:
def get_diff_central_atom_filter(df_nnlist=df_nnlist, df_coords=df_coords):
    """
    dependency: get_all_non_cluster_atom()
    
    To convert list to filter, Use thie func.
    
    param1: df_nnlist=df_nnlist
    param2: df_coords=df_coords
    
    """
    
    diff_central_atom_list = get_all_non_cluster_atom(df_nnlist=df_nnlist, df_coords=df_coords)
    diff_central_atom_filter = df_coords['central atom'].apply(lambda row: row in diff_central_atom_list)
    return diff_central_atom_filter

### get_right_valueとcluster_central_atom_listを用いて，クラスタに入っている全原子のid(central atom)を得る．

In [20]:
# 1重リストに変換
flat_list = [item for sublist in cluster_all_atom_list_dubled for item in sublist]
# 重複削除
cluster_all_atom_set = set(flat_list)
# cluster_all_atom_list_fix = list(set(flat_list))
# print(cluster_all_atom_list_fix)

NameError: name 'cluster_all_atom_list_dubled' is not defined

In [33]:
cluster_all_atom_set

{1, 2, 3, 4, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}

#### cluster_all_atom_list_fixに含まれないcentral atomを抽出して、さらにdf_coord[]から得る．

In [34]:
all_central_atom_set = set(df_coords['central atom'].tolist())

In [35]:
all_central_atom_set

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}

In [36]:
# 差分を取得
diff_central_atom_list = list(all_central_atom_set.difference(cluster_all_atom_set))
diff_central_atom_list

[8, 5, 6, 7]

### diff_central_atom_listをフィルター化する → df_coords[]に代入する

##### ある値がリストに含まれるかを判定する  ->  ex) 20 in diff_central_atom_list

In [37]:
20 in diff_central_atom_list

False

In [38]:
diff_central_atom_filter = df_coords['central atom'].apply(lambda row: row in diff_central_atom_list)
# print(diff_central_atom_filter)

In [56]:
# df_coords[diff_central_atom_filter]

,central atom,x,y,z,Species
4,5,0.250000000000000,0.416310000000000,0.754900000000000,Ba
5,6,0.250000000000000,0.083690000000000,0.254900000000000,Ba
6,7,0.750000000000000,0.583690000000000,0.245100000000000,Ba
7,8,0.750000000000000,0.916310000000000,0.745100000000000,Ba

In [59]:
df_coords[get_diff_central_atom_filter(df_nnlist=df_nnlist, df_coords=df_coords)]

,central atom,x,y,z,Species
4,5,0.250000000000000,0.416310000000000,0.754900000000000,Ba
5,6,0.250000000000000,0.083690000000000,0.254900000000000,Ba
6,7,0.750000000000000,0.583690000000000,0.245100000000000,Ba
7,8,0.750000000000000,0.916310000000000,0.745100000000000,Ba

<!-- ### 2つのフィルターをorで結合する関数 -->

In [ ]:
# def get_union_filter(filter1=diff_central_atom_filter, filter2=):


#     return central_atom_filter_fix

### df_coords[]で、クラスタの中心の絶対座標のフィルターと重複削除された残りの絶対座標のフィルターを結合してフィルターする

#### 過不足のないcentral atomのfilterが完成

In [67]:
# diff_central_atom_filter

In [68]:
# get_elem_max_filter(df_nnlist=df_nnlist)

In [23]:
diff_central_atom_filter = get_diff_central_atom_filter()
central_atom_filter_fix = diff_central_atom_filter | get_elem_max_filter(df_nnlist=df_nnlist)
central_atom_filter_fix

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
Name: central atom, dtype: bool

#### クラスタ後の新しい絶対座標を得る

In [24]:
df_coords_abs_center = df_coords[central_atom_filter_fix]
df_coords_abs_center

,central atom,x,y,z,Species
0,1,0.000000000000000,0.764000000000000,0.153000000000000,C
1,2,0.500000000000000,0.736000000000000,0.653000000000000,C
2,3,0.000000000000000,0.236000000000000,0.847000000000000,C
3,4,0.500000000000000,0.764000000000000,0.153000000000000,C
4,5,0.000000000000000,0.736000000000000,0.653000000000000,C
5,6,0.500000000000000,0.264000000000000,0.347000000000000,C
6,7,0.500000000000000,0.236000000000000,0.847000000000000,C
7,8,0.000000000000000,0.264000000000000,0.347000000000000,C
24,25,0.199000000000000,0.691000000000000,0.153000000000000,O
25,26,0.301000000000000,0.809000000000000,0.653000000000000,O
26,27,0.801000000000000,0.309000000000000,0.847000000000000,O
27,28,0.301000000000000,0.691000000000000,0.153000000000000,O
28,29,0.199000000000000,0.809000000000000,0.653000000000000,O
29,30,0.699000000000000,0.191000000000000,0.347000000000000,O
30,31,0.699000000000000,0.309000000000000,0.847000000000000,O
31,32,0.801000000000000,0.191000000000000,0.347000000000000,O

#### クラスタ後の新しい絶対座標を文字列→数値に変換 する関数

In [25]:
def df_elem_str2num(df_coords_abs_center=df_coords_abs_center):
    
    # 文字列を数値化する
    df_coords_abs_center['x'] = pd.to_numeric(df_coords_abs_center['x'], errors='coerce')
    df_coords_abs_center['y'] = pd.to_numeric(df_coords_abs_center['y'], errors='coerce')
    df_coords_abs_center['z'] = pd.to_numeric(df_coords_abs_center['z'], errors='coerce')
    
    return df_coords_abs_center

In [26]:
df_coords_abs_center = df_elem_str2num(df_coords_abs_center=df_coords_abs_center)

/tmp/ipykernel_29689/2352175167.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coords_abs_center['x'] = pd.to_numeric(df_coords_abs_center['x'], errors='coerce')
/tmp/ipykernel_29689/2352175167.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coords_abs_center['y'] = pd.to_numeric(df_coords_abs_center['y'], errors='coerce')
/tmp/ipykernel_29689/2352175167.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coords_abs_center['z'] = pd.to_numeric(df_coords_abs_center['z'], errors='coerce')

In [27]:
# 数値化したクラスタ後の絶対座標
df_coords_abs_center

    central atom        x        y        z Species
0              1 0.000000 0.764000 0.153000       C
1              2 0.500000 0.736000 0.653000       C
2              3 0.000000 0.236000 0.847000       C
3              4 0.500000 0.764000 0.153000       C
4              5 0.000000 0.736000 0.653000       C
5              6 0.500000 0.264000 0.347000       C
6              7 0.500000 0.236000 0.847000       C
7              8 0.000000 0.264000 0.347000       C
24            25 0.199000 0.691000 0.153000       O
25            26 0.301000 0.809000 0.653000       O
26            27 0.801000 0.309000 0.847000       O
27            28 0.301000 0.691000 0.153000       O
28            29 0.199000 0.809000 0.653000       O
29            30 0.699000 0.191000 0.347000       O
30            31 0.699000 0.309000 0.847000       O
31            32 0.801000 0.191000 0.347000       O

#### クラスタの相対中心座標を計算

In [28]:
df_nnlist_grouped = df_nnlist.groupby('central atom').mean()
# central atomカラムでgroupby.mean()した後、index列(central atom)をカラムにする   
df_nnlist_grouped = df_nnlist_grouped.reset_index()

/tmp/ipykernel_29689/3839055567.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_nnlist_grouped = df_nnlist.groupby('central atom').mean()

In [29]:
df_cluster_relative_center = df_nnlist_grouped[central_atom_filter_fix]
df_cluster_relative_center

,central atom,neighboring atom,distance,X,Y,Z,unitcell_x,unitcell_y,unitcell_z
0,1,16.400000,1.179789,0.516600,-0.308235,-0.188068,0.000000,0.000000,0.000000
1,2,17.800000,1.179789,-0.516600,0.308235,-0.188068,0.000000,0.000000,0.000000
2,3,17.800000,1.179789,-0.516600,0.308235,0.188068,-0.400000,0.000000,0.200000
3,4,18.400000,1.179789,-0.516600,-0.308235,-0.188068,0.000000,0.000000,0.000000
4,5,19.400000,1.179789,0.516600,0.308235,-0.188068,0.000000,0.000000,0.000000
5,6,20.000000,1.179789,0.516600,-0.308235,0.188068,0.000000,0.000000,0.000000
6,7,20.000000,1.179789,0.516600,0.308235,0.188068,0.000000,0.000000,0.200000
7,8,21.400000,1.179789,-0.516600,-0.308235,0.188068,-0.400000,0.000000,0.000000
24,25,13.800000,1.013284,0.005166,0.064357,-0.188068,0.000000,0.000000,0.000000
25,26,15.200000,1.013284,-0.005166,-0.064357,-0.188068,0.000000,0.000000,0.000000
26,27,15.400000,1.013284,-0.005166,-0.064357,0.188068,0.400000,0.000000,0.200000
27,28,14.600000,1.013284,-0.005166,0.064357,-0.188068,0.000000,0.000000,0.000000
28,29,15.600000,1.013284,0.005166,-0.064357,-0.188068,0.000000,0.000000,0.000000
29,30,17.200000,1.013284,0.005166,0.064357,0.188068,0.200000,0.000000,0.000000
30,31,16.000000,1.013284,0.005166,-0.064357,0.188068,0.200000,0.000000,0.200000
31,32,17.800000,1.013284,-0.005166,0.064357,0.188068,0.400000,0.000000,0.000000

### 絶対座標 + 相対座標の計算

In [30]:
def get_clusterd_coords(df_abs=df_coords_abs_center, df_relative=df_cluster_relative_center):
    df_coords_x = df_abs['x'] + df_relative['X']
    df_coords_y = df_abs['y'] + df_relative['Y']
    df_coords_z = df_abs['z'] + df_relative['Z']
    df_coords_species = df_abs['Species']

    # カラム名を指定してデータフレームを作成
    df_coords_fix = pd.DataFrame({
        'X': df_coords_x,
        'Y': df_coords_y,
        'Z': df_coords_z,
        'Species': df_coords_species,
    })

    return df_coords_fix

In [31]:
df_coords_fix = get_clusterd_coords(df_abs=df_coords_abs_center, df_relative=df_cluster_relative_center)
df_coords_fix

           X         Y         Z Species
0   0.516600  0.455765 -0.035068       C
1  -0.016600  1.044235  0.464932       C
2  -0.516600  0.544235  1.035068       C
3  -0.016600  0.455765 -0.035068       C
4   0.516600  1.044235  0.464932       C
5   1.016600 -0.044235  0.535068       C
6   1.016600  0.544235  1.035068       C
7  -0.516600 -0.044235  0.535068       C
24  0.204166  0.755357 -0.035068       O
25  0.295834  0.744643  0.464932       O
26  0.795834  0.244643  1.035068       O
27  0.295834  0.755357 -0.035068       O
28  0.204166  0.744643  0.464932       O
29  0.704166  0.255357  0.535068       O
30  0.704166  0.244643  1.035068       O
31  0.795834  0.255357  0.535068       O

In [32]:
### 元のPOSCARファイルから5行目までを抽出して、新しいPOSCARファイルに書き込む関数

In [33]:
# import os

# # 作成するフォルダのパスを指定
# folder_name = "gen_data"

# # フォルダを作成
# os.makedirs(folder_name, exist_ok=True)

# print(f"{folder_name} フォルダを作成しました。")

In [34]:
import os

def df2poscar(df=df_coords_fix, original_file="./POSCAR", output_file="gen_data/POSCAR"):
    """
    Writing the DataFrame(:df_coords_fix) to a POSCAR file.
    param1: DataFrame that has 'X', 'Y', 'Z' columns about coords.
    param2: original POSCAR file
    param3: generated POSCAR file
    """
    
    # 出力先のフォルダを作成
    def make_folder(folder_name = "gen_data"):
        # 作成するフォルダのパスを指定
        folder_name = "gen_data"

        # フォルダを作成
        os.makedirs(folder_name, exist_ok=True)

    
    # df_coords_fixを文字列に変換
    def df2str(df):
        df_coords_fix_str = df[['X', 'Y', 'Z']].to_string(header=False, index=False, index_names=False)
        return df_coords_fix_str
    
    # df_coords_fixから元素種を文字列として抽出する関数
    def return_species(df):
        speies_0 = df['Species'].unique()[0]
        speies_1 = df['Species'].unique()[1]
        num_C = len(df[df['Species'] == speies_0])
        num_Ba = len(df[df['Species'] == speies_1])

        species_line = f"""   {speies_0}   {speies_1}
       {num_C}   {num_Ba}"""

       #  species_line = f"""   {speies_0}
       # {num_C}   """
        
        return species_line

    
    # 元のPOSCARファイルの5行目までを抽出し，新しいファイルに書き込む
    def wirte_header2poscar():
        # 最初の5行を抽出
        with open(original_file, 'r') as infile:
            lines = infile.readlines()[:5]
        # 新しいPOSCARファイルに書き込む
        with open(output_file, 'w') as outfile:
            outfile.writelines(lines)
    
    
    # 新しいPOSCARファイルに書き込んでいく
    def write_species2poscar():
        with open(output_file, 'a') as file:
            # すでに存在するテキストファイルに元素種を追記
            file.write(return_species(df) + '\n')
            # 元素種まで書かれたファイルにDirectという文字をを追記
            file.write('Direct\n' )
            # 直交座標を追記
            file.write(df2str(df))

            
    # 関数をcall
    make_folder()
    df2str(df)
    wirte_header2poscar()
    write_species2poscar()
    
    print(f"{output_file} にクラスタ化後の内容が書き込まれました。")

In [35]:
df2poscar()

gen_data/POSCAR にクラスタ化後の内容が書き込まれました。

#### 編集後のposcarファイルをASEで可視化

In [41]:
from ase.io import read, write

output_file="gen_data/POSCAR"
# POSCARファイルの読み込み
atoms = read(output_file)

# POSCARファイルの描画
from ase.visualize import view, ngl
ngl.view_ngl(atoms)

HBox(children=(NGLWidget(), VBox(children=(Dropdown(description='Show', options=('All', 'O', 'C'), value='All'…

In [38]:
from ase.io import read, write
# POSCARファイルの読み込み
atoms = read('POSCAR')

# POSCARファイルの描画
from ase.visualize import view, ngl
ngl.view_ngl(atoms)

HBox(children=(NGLWidget(), VBox(children=(Dropdown(description='Show', options=('All', 'O', 'C', 'Pb'), value…

#### 編集後のposcarファイルをVESTAで可視化

In [39]:
from my_package import visualize
output_file="gen_data/POSCAR"
visualize.vesta(output_file)

(VESTA-gui:29846): Gtk-WARNING **: 19:09:50.596: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-WARNING **: 19:09:50.597: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-WARNING **: 19:09:50.597: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-WARNING **: 19:09:50.597: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-CRITICAL **: 19:09:50.598: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(VESTA-gui:29846): Gtk-WARNING **: 19:09:50.795: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-WARNING **: 19:09:50.795: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-CRITICAL **: 19:09:50.795: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(VESTA-gui:29846): Gtk-WARNING **: 19:09:51.053: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-WARNING **: 19:09:51.053: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-WARNING **: 19:09:51.054: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-WARNING **: 19:09:51.054: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-CRITICAL **: 19:09:51.055: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(VESTA-gui:29846): Gtk-WARNING **: 19:09:51.274: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-WARNING **: 19:09:51.275: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:29846): Gtk-CRITICAL **: 19:09:51.275: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

type=0 format=0 nitems=0 atom=276 252
workspace= 0 : -1, x=10, y=31; Screen_W=1504