### python3のバージョンを確認

In [219]:
!which python3

/usr/bin/python3

### packageからVESTAを読みだす

In [220]:
from my_package import visualize

### ASEでPOSCARファイルを可視化

In [221]:
from ase.io import read, write
# POSCARファイルの読み込み
atoms = read('POSCAR')

# POSCARファイルの描画
from ase.visualize import view, ngl
ngl.view_ngl(atoms)

HBox(children=(NGLWidget(), VBox(children=(Dropdown(description='Show', options=('All', 'Sr', 'C', 'O'), value…

### Converting a POSCAR file to a DataFrame

In [222]:
from my_package.textfile2df import poscar2df_coords 

df_coords = poscar2df_coords(filename='./POSCAR')
df_coords

,central atom,x,y,z,Species
0,1,0.833700000000000,0.115500000000000,0.979000000000000,O
1,2,0.166300000000000,0.884500000000000,0.021000000000000,O
2,3,0.166300000000000,0.615500000000000,0.521000000000000,O
3,4,0.833700000000000,0.384500000000000,0.479000000000000,O
4,5,0.894800000000000,0.901500000000000,0.647000000000000,O
5,6,0.105200000000000,0.098500000000000,0.353000000000000,O
6,7,0.105200000000000,0.401500000000000,0.853000000000000,O
7,8,0.894800000000000,0.598500000000000,0.147000000000000,O
8,9,0.542500000000000,0.969200000000000,0.802000000000000,O
9,10,0.457500000000000,0.030800000000000,0.198000000000000,O
10,11,0.457500000000000,0.469200000000000,0.698000000000000,O
11,12,0.542500000000000,0.530800000000000,0.302000000000000,O
12,13,0.403900000000000,0.183500000000000,0.799100000000000,O
13,14,0.596100000000000,0.816500000000000,0.200900000000000,O
14,15,0.596100000000000,0.683500000000000,0.700900000000000,O
15,16,0.403900000000000,0.316500000000000,0.299100000000000,O
16,17,0.048100000000000,0.108400000000000,0.697800000000000,O
17,18,0.951900000000000,0.891600000000000,0.302200000000000,O
18,19,0.951900000000000,0.608400000000000,0.802200000000000,O
19,20,0.048100000000000,0.391600000000000,0.197800000000000,O
20,21,0.705200000000000,0.329000000000000,0.894400000000000,O
21,22,0.294800000000000,0.671000000000000,0.105600000000000,O
22,23,0.294800000000000,0.829000000000000,0.605600000000000,O
23,24,0.705200000000000,0.171000000000000,0.394400000000000,O
24,25,0.536000000000000,0.103000000000000,0.829000000000000,C
25,26,0.464000000000000,0.897000000000000,0.171000000000000,C
26,27,0.464000000000000,0.603000000000000,0.671000000000000,C
27,28,0.536000000000000,0.397000000000000,0.329000000000000,C
28,29,0.708000000000000,0.189000000000000,0.909000000000000,C
29,30,0.292000000000000,0.811000000000000,0.091000000000000,C
30,31,0.292000000000000,0.689000000000000,0.591000000000000,C
31,32,0.708000000000000,0.311000000000000,0.409000000000000,C
32,33,0.973000000000000,0.998000000000000,0.601000000000000,C
33,34,0.027000000000000,0.002000000000000,0.399000000000000,C
34,35,0.027000000000000,0.498000000000000,0.899000000000000,C
35,36,0.973000000000000,0.502000000000000,0.101000000000000,C
36,37,0.827300000000000,0.826100000000000,0.956800000000000,Sr
37,38,0.172700000000000,0.173900000000000,0.043200000000000,Sr
38,39,0.172700000000000,0.326100000000000,0.543200000000000,Sr
39,40,0.827300000000000,0.673900000000000,0.456800000000000,Sr

### converting POSCAR.nnlist to df_nnlist

In [223]:
from my_package.textfile2df import nnlist2df
import pandas as pd

#行の表示数の上限を撤廃
pd.set_option('display.max_rows', None)

df_nnlist = nnlist2df(POSCAR_nnlist='POSCAR.nnlist')
df_nnlist

,central atom,neighboring atom,distance,X,Y,Z,unitcell_x,unitcell_y,unitcell_z,central species,neighboring species
0,1,1,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
1,1,29,1.227922,-0.893898,0.676568,-0.500995,0,0,0,O,C
2,2,2,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
3,2,30,1.227922,0.893898,-0.676567,0.500995,0,0,0,O,C
4,3,3,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
5,3,31,1.227922,0.893898,0.676567,0.500995,0,0,0,O,C
6,4,4,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
7,4,32,1.227922,-0.893898,-0.676568,-0.500995,0,0,0,O,C
8,5,5,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
9,5,33,1.174074,0.693553,0.888283,-0.329225,0,0,0,O,C
10,6,6,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
11,6,34,1.174074,-0.693553,-0.888283,0.329225,0,0,0,O,C
12,7,7,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
13,7,35,1.174074,-0.693553,0.888282,0.329225,0,0,0,O,C
14,8,8,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
15,8,36,1.174074,0.693553,-0.888283,-0.329225,0,0,0,O,C
16,9,9,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
17,9,25,1.250177,-0.093221,1.231629,0.193241,0,1,0,O,C
18,10,10,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
19,10,26,1.250177,0.093221,-1.231629,-0.193241,0,-1,0,O,C
20,11,11,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
21,11,27,1.250177,0.093221,1.231629,-0.193241,0,0,0,O,C
22,12,12,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
23,12,28,1.250177,-0.093221,-1.231629,0.193241,0,0,0,O,C
24,13,13,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
25,13,25,1.267982,1.006429,-0.741003,0.213996,0,0,0,O,C
26,14,14,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
27,14,26,1.267982,-1.006429,0.741003,-0.213996,0,0,0,O,C
28,15,15,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
29,15,27,1.267982,-1.006429,-0.741003,-0.213996,0,0,0,O,C
30,16,16,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
31,16,28,1.267982,1.006429,0.741003,0.213996,0,0,0,O,C
32,17,17,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
33,17,33,1.309548,-0.449679,-1.016232,-0.692804,-1,-1,0,O,C
34,18,18,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
35,18,34,1.309548,0.449679,1.016232,0.692804,1,1,0,O,C
36,19,19,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
37,19,35,1.309548,0.449679,-1.016232,0.692804,1,0,0,O,C
38,20,20,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
39,20,36,1.309548,-0.449679,1.016232,-0.692804,-1,0,0,O,C
40,21,21,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
41,21,29,1.292929,-0.000104,-1.288700,0.104493,0,0,0,O,C
42,22,22,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
43,22,30,1.292929,0.000104,1.288700,-0.104493,0,0,0,O,C
44,23,23,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
45,23,31,1.292929,0.000104,-1.288700,-0.104493,0,0,0,O,C
46,24,24,0.000000,0.000000,0.000000,0.000000,0,0,0,O,O
47,24,32,1.292929,-0.000104,1.288700,0.104493,0,0,0,O,C
48,25,9,1.250177,0.093221,-1.231629,-0.193241,0,-1,0,C,O
49,25,13,1.267982,-1.006429,0.741003,-0.213996,0,0,0,C,O
50,25,25,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
51,25,29,1.584445,1.247380,0.791630,0.572566,0,0,0,C,C
52,26,10,1.250177,-0.093221,1.231629,0.193241,0,1,0,C,O
53,26,14,1.267982,1.006429,-0.741003,0.213996,0,0,0,C,O
54,26,26,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
55,26,30,1.584445,-1.247380,-0.791630,-0.572566,0,0,0,C,C
56,27,11,1.250177,-0.093221,-1.231629,0.193241,0,0,0,C,O
57,27,15,1.267982,1.006429,0.741003,0.213996,0,0,0,C,O
58,27,27,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
59,27,31,1.584445,-1.247380,0.791630,-0.572566,0,0,0,C,C
60,28,12,1.250177,0.093221,1.231629,-0.193241,0,0,0,C,O
61,28,16,1.267982,-1.006429,-0.741003,-0.213996,0,0,0,C,O
62,28,28,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
63,28,32,1.584445,1.247380,-0.791630,0.572566,0,0,0,C,C
64,29,1,1.227922,0.893898,-0.676568,0.500995,0,0,0,C,O
65,29,21,1.292929,0.000104,1.288700,-0.104493,0,0,0,C,O
66,29,25,1.584445,-1.247380,-0.791630,-0.572566,0,0,0,C,C
67,29,29,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
68,30,2,1.227922,-0.893898,0.676567,-0.500995,0,0,0,C,O
69,30,22,1.292929,-0.000104,-1.288700,0.104493,0,0,0,C,O
70,30,26,1.584445,1.247380,0.791630,0.572566,0,0,0,C,C
71,30,30,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
72,31,3,1.227922,-0.893898,-0.676567,-0.500995,0,0,0,C,O
73,31,23,1.292929,-0.000104,1.288700,0.104493,0,0,0,C,O
74,31,27,1.584445,1.247380,-0.791630,0.572566,0,0,0,C,C
75,31,31,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
76,32,4,1.227922,0.893898,0.676568,0.500995,0,0,0,C,O
77,32,24,1.292929,0.000104,-1.288700,-0.104493,0,0,0,C,O
78,32,28,1.584445,-1.247380,0.791630,-0.572566,0,0,0,C,C
79,32,32,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
80,33,5,1.174074,-0.693553,-0.888283,0.329225,0,0,0,C,O
81,33,17,1.309548,0.449679,1.016232,0.692804,1,1,0,C,O
82,33,33,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
83,33,34,1.624623,0.740212,0.036820,-1.445728,1,1,0,C,C
84,34,6,1.174074,0.693553,0.888283,-0.329225,0,0,0,C,O
85,34,18,1.309548,-0.449679,-1.016232,-0.692804,-1,-1,0,C,O
86,34,33,1.624623,-0.740212,-0.036820,1.445728,-1,-1,0,C,C
87,34,34,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
88,35,7,1.174074,0.693553,-0.888282,-0.329225,0,0,0,C,O
89,35,19,1.309548,-0.449679,1.016232,-0.692804,-1,0,0,C,O
90,35,35,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
91,35,36,1.624623,-0.740212,0.036820,1.445728,-1,0,1,C,C
92,36,8,1.174074,-0.693553,0.888283,0.329225,0,0,0,C,O
93,36,20,1.309548,0.449679,-1.016232,0.692804,1,0,0,C,O
94,36,35,1.624623,0.740212,-0.036820,-1.445728,1,0,-1,C,C
95,36,36,0.000000,0.000000,0.000000,0.000000,0,0,0,C,C
96,37,37,0.000000,0.000000,0.000000,0.000000,0,0,0,Sr,Sr
97,38,38,0.000000,0.000000,0.000000,0.000000,0,0,0,Sr,Sr
98,39,39,0.000000,0.000000,0.000000,0.000000,0,0,0,Sr,Sr
99,40,40,0.000000,0.000000,0.000000,0.000000,0,0,0,Sr,Sr

In [224]:
df_nnlist[['central atom', 'neighboring atom']].to_csv('central_neighboring_atom.csv', index=False)

In [225]:
# df_nnlist['diff_central_neighbor'] = abs(df_nnlist['central atom'] - df_nnlist['neighboring atom'])

#### df_nnlist.groupby('central atom').count()['neighboring atom']で最も要素数の多いもののcentral atomをクラスタとして得る．
#### → クラスタ化されたcentral atomを重複削除する　
#### → 新しいcentral atomのリストを得る

In [226]:
df_nnlist.groupby('central atom').count()['neighboring atom']

central atom
1     2
2     2
3     2
4     2
5     2
6     2
7     2
8     2
9     2
10    2
11    2
12    2
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    2
21    2
22    2
23    2
24    2
25    4
26    4
27    4
28    4
29    4
30    4
31    4
32    4
33    4
34    4
35    4
36    4
37    1
38    1
39    1
40    1
Name: neighboring atom, dtype: int64

#### df_nnlist.groupby('central atom').count()['neighboring atom']で最も要素数の多いもののcentral atomをクラスタとして得る．

In [227]:
elem_max_num = df_nnlist.groupby('central atom').count()['neighboring atom'].max()

In [228]:
elem_max_num_filter = df_nnlist.groupby('central atom').count()['neighboring atom'] == elem_max_num

In [229]:
elem_max_num_filter

central atom
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37    False
38    False
39    False
40    False
Name: neighboring atom, dtype: bool

In [230]:
elem_max_num_filter_list = elem_max_num_filter.to_list()

#### メモ：df_coords[elem_max_num_filter_list] によりクラスタ中心の絶対座標を得る

In [231]:
# df_coords[elem_max_num_filter_list]

#### df_nnlistで入力：central atom → 出力：neighboring atom を返す関数get_right_valueを作成．

In [232]:
import pandas as pd

# 入力値が左側の数値と同じ場合、対応する右側の数値を返す関数
def get_right_value(input_value):
    # 左側の列から対応する行を選択し、右側の数値を取得
    # result = df_nnlist[df_nnlist['central atom'] == input_value]['neighboring atom'].values
    result = df_nnlist[df_nnlist['central atom'] == input_value]['neighboring atom'].tolist()
    return result

# 関数をテスト
get_right_value(1)

[1, 29]

#### クラスタ中心のcentral atom(id的な番号)の一覧を得る

In [233]:
cluster_central_atom_list = df_coords[elem_max_num_filter_list]['central atom'].tolist()
print(cluster_central_atom_list)

[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]

### get_right_valueとcluster_central_atom_listを用いて，クラスタに入っている全原子のid(central atom)を得る．

In [234]:
# 1重リストに変換
flat_list = [item for sublist in cluster_all_atom_list for item in sublist]
# 重複削除
cluster_all_atom_set = set(flat_list)
# cluster_all_atom_list_fix = list(set(flat_list))
# print(cluster_all_atom_list_fix)

#### cluster_all_atom_list_fixに含まれないcentral atomを抽出して、さらにdf_coord[]から得る．

In [235]:
all_central_atom_set = set(df_coords['central atom'].tolist())

In [236]:
# 差分を取得
diff_central_atom_list = list(all_central_atom_set.difference(cluster_all_atom_set))
diff_central_atom_list

[40, 37, 38, 39]

### diff_central_atom_listをフィルター化する → df_coords[]に代入する

##### ある値がリストに含まれるかを判定する  ->  ex) 20 in diff_central_atom_list

In [237]:
20 in diff_central_atom_list

False

In [238]:
diff_central_atom_filter = df_coords['central atom'].apply(lambda row: row in diff_central_atom_list)
# print(diff_central_atom_filter)

In [239]:
df_coords[diff_central_atom_filter]

,central atom,x,y,z,Species
36,37,0.827300000000000,0.826100000000000,0.956800000000000,Sr
37,38,0.172700000000000,0.173900000000000,0.043200000000000,Sr
38,39,0.172700000000000,0.326100000000000,0.543200000000000,Sr
39,40,0.827300000000000,0.673900000000000,0.456800000000000,Sr

In [240]:
df_coords[pd.Series(elem_max_num_filter_list)]

,central atom,x,y,z,Species
24,25,0.536000000000000,0.103000000000000,0.829000000000000,C
25,26,0.464000000000000,0.897000000000000,0.171000000000000,C
26,27,0.464000000000000,0.603000000000000,0.671000000000000,C
27,28,0.536000000000000,0.397000000000000,0.329000000000000,C
28,29,0.708000000000000,0.189000000000000,0.909000000000000,C
29,30,0.292000000000000,0.811000000000000,0.091000000000000,C
30,31,0.292000000000000,0.689000000000000,0.591000000000000,C
31,32,0.708000000000000,0.311000000000000,0.409000000000000,C
32,33,0.973000000000000,0.998000000000000,0.601000000000000,C
33,34,0.027000000000000,0.002000000000000,0.399000000000000,C
34,35,0.027000000000000,0.498000000000000,0.899000000000000,C
35,36,0.973000000000000,0.502000000000000,0.101000000000000,C

In [241]:
pd.Series(elem_max_num_filter_list)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36    False
37    False
38    False
39    False
dtype: bool

### df_coords[]で、クラスタの中心の絶対座標のフィルターと重複削除された残りの絶対座標のフィルターを結合してフィルターする

#### 過不足のないcentral atomのfilterが完成

In [242]:
central_atom_filter_fix = diff_central_atom_filter | pd.Series(elem_max_num_filter_list)

#### クラスタ後の新しい絶対座標を得る

In [243]:
df_coords_abs_center = df_coords[central_atom_filter_fix]
df_coords_abs_center

,central atom,x,y,z,Species
24,25,0.536000000000000,0.103000000000000,0.829000000000000,C
25,26,0.464000000000000,0.897000000000000,0.171000000000000,C
26,27,0.464000000000000,0.603000000000000,0.671000000000000,C
27,28,0.536000000000000,0.397000000000000,0.329000000000000,C
28,29,0.708000000000000,0.189000000000000,0.909000000000000,C
29,30,0.292000000000000,0.811000000000000,0.091000000000000,C
30,31,0.292000000000000,0.689000000000000,0.591000000000000,C
31,32,0.708000000000000,0.311000000000000,0.409000000000000,C
32,33,0.973000000000000,0.998000000000000,0.601000000000000,C
33,34,0.027000000000000,0.002000000000000,0.399000000000000,C
34,35,0.027000000000000,0.498000000000000,0.899000000000000,C
35,36,0.973000000000000,0.502000000000000,0.101000000000000,C
36,37,0.827300000000000,0.826100000000000,0.956800000000000,Sr
37,38,0.172700000000000,0.173900000000000,0.043200000000000,Sr
38,39,0.172700000000000,0.326100000000000,0.543200000000000,Sr
39,40,0.827300000000000,0.673900000000000,0.456800000000000,Sr

#### クラスタ後の新しい絶対座標を文字列→数値に変換

In [244]:
# 文字列を数値化する
df_coords_abs_center['x'] = pd.to_numeric(df_coords_abs_center['x'], errors='coerce')
df_coords_abs_center['y'] = pd.to_numeric(df_coords_abs_center['y'], errors='coerce')
df_coords_abs_center['z'] = pd.to_numeric(df_coords_abs_center['z'], errors='coerce')

/tmp/ipykernel_21594/1545705368.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coords_abs_center['x'] = pd.to_numeric(df_coords_abs_center['x'], errors='coerce')
/tmp/ipykernel_21594/1545705368.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coords_abs_center['y'] = pd.to_numeric(df_coords_abs_center['y'], errors='coerce')
/tmp/ipykernel_21594/1545705368.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coords_abs_center['z'] = pd.to_numeric(df_coords_abs_center['z'], errors='coerce')

In [245]:
df_coords_abs_center

    central atom        x        y        z Species
24            25 0.536000 0.103000 0.829000       C
25            26 0.464000 0.897000 0.171000       C
26            27 0.464000 0.603000 0.671000       C
27            28 0.536000 0.397000 0.329000       C
28            29 0.708000 0.189000 0.909000       C
29            30 0.292000 0.811000 0.091000       C
30            31 0.292000 0.689000 0.591000       C
31            32 0.708000 0.311000 0.409000       C
32            33 0.973000 0.998000 0.601000       C
33            34 0.027000 0.002000 0.399000       C
34            35 0.027000 0.498000 0.899000       C
35            36 0.973000 0.502000 0.101000       C
36            37 0.827300 0.826100 0.956800      Sr
37            38 0.172700 0.173900 0.043200      Sr
38            39 0.172700 0.326100 0.543200      Sr
39            40 0.827300 0.673900 0.456800      Sr

#### クラスタの相対中心座標を計算

In [246]:
df_nnlist_grouped = df_nnlist.groupby('central atom').mean()
# central atomカラムでgroupby.mean()した後、index列(central atom)をカラムにする   
df_nnlist_grouped = df_nnlist_grouped.reset_index()

/tmp/ipykernel_21594/3839055567.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_nnlist_grouped = df_nnlist.groupby('central atom').mean()

In [247]:
df_cluster_relative_center = df_nnlist_grouped[central_atom_filter_fix]
df_cluster_relative_center

,central atom,neighboring atom,distance,X,Y,Z,unitcell_x,unitcell_y,unitcell_z
24,25,19.000000,1.025651,0.083543,0.075251,0.041332,0.000000,-0.250000,0.000000
25,26,20.000000,1.025651,-0.083543,-0.075251,-0.041332,0.000000,0.250000,0.000000
26,27,21.000000,1.025651,-0.083543,0.075251,-0.041332,0.000000,0.000000,0.000000
27,28,22.000000,1.025651,0.083543,-0.075251,0.041332,0.000000,0.000000,0.000000
28,29,19.000000,1.026324,-0.088344,-0.044874,-0.044016,0.000000,0.000000,0.000000
29,30,20.000000,1.026324,0.088344,0.044874,0.044016,0.000000,0.000000,0.000000
30,31,21.000000,1.026324,0.088344,-0.044874,0.044016,0.000000,0.000000,0.000000
31,32,22.000000,1.026324,-0.088344,0.044874,-0.044016,0.000000,0.000000,0.000000
32,33,22.250000,1.027061,0.124085,0.041192,-0.105925,0.500000,0.500000,0.000000
33,34,22.750000,1.027061,-0.124085,-0.041192,0.105925,-0.500000,-0.500000,0.000000
34,35,24.250000,1.027061,-0.124085,0.041192,0.105925,-0.500000,0.000000,0.250000
35,36,24.750000,1.027061,0.124085,-0.041192,-0.105925,0.500000,0.000000,-0.250000
36,37,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,38,38.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,39,39.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,40,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

### 絶対座標 + 相対座標の計算

In [248]:
def get_clusterd_coords(df_abs=df_coords_abs_center, df_relative=df_cluster_relative_center):
    df_coords_x = df_abs['x'] + df_relative['X']
    df_coords_y = df_abs['y'] + df_relative['Y']
    df_coords_z = df_abs['z'] + df_relative['Z']
    df_coords_species = df_abs['Species']

    # カラム名を指定してデータフレームを作成
    df_coords_fix = pd.DataFrame({
        'X': df_coords_x,
        'Y': df_coords_y,
        'Z': df_coords_z,
        'Species': df_coords_species,
    })

    return df_coords_fix

In [249]:
df_coords_fix = get_clusterd_coords(df_abs=df_coords_abs_center, df_relative=df_cluster_relative_center)
df_coords_fix

           X         Y         Z Species
24  0.619543  0.178251  0.870332       C
25  0.380457  0.821749  0.129668       C
26  0.380457  0.678251  0.629668       C
27  0.619543  0.321749  0.370332       C
28  0.619655  0.144126  0.864984       C
29  0.380344  0.855874  0.135016       C
30  0.380344  0.644126  0.635016       C
31  0.619655  0.355874  0.364984       C
32  1.097085  1.039192  0.495075       C
33 -0.097085 -0.039192  0.504925       C
34 -0.097085  0.539192  1.004925       C
35  1.097085  0.460808 -0.004925       C
36  0.827300  0.826100  0.956800      Sr
37  0.172700  0.173900  0.043200      Sr
38  0.172700  0.326100  0.543200      Sr
39  0.827300  0.673900  0.456800      Sr

In [250]:
### 元のPOSCARファイルから5行目までを抽出して、新しいPOSCARファイルに書き込む関数

In [251]:
def df2poscar(df=df_coords_fix, original_file="./POSCAR", output_file="gen_data/POSCAR"):
    """
    Writing the DataFrame(:df_coords_fix) to a POSCAR file.
    param1: DataFrame that has 'X', 'Y', 'Z' columns about coords.
    param2: original POSCAR file
    param3: generated POSCAR file
    """
    
    # df_coords_fixを文字列に変換
    def df2str(df):
        df_coords_fix_str = df[['X', 'Y', 'Z']].to_string(header=False, index=False, index_names=False)
        return df_coords_fix_str
    
    # df_coords_fixから元素種を文字列として抽出する関数
    def return_species(df):
        speies_0 = df['Species'].unique()[0]
        speies_1 = df['Species'].unique()[1]
        num_C = len(df[df['Species'] == speies_0])
        num_Ba = len(df[df['Species'] == speies_1])

        species_line = f"""   {speies_0}   {speies_1}
       {num_C}   {num_Ba}"""

       #  species_line = f"""   {speies_0}
       # {num_C}   """
        
        return species_line

    
    # 元のPOSCARファイルの5行目までを抽出し，新しいファイルに書き込む
    def wirte_header2poscar():
        # 最初の5行を抽出
        with open(original_file, 'r') as infile:
            lines = infile.readlines()[:5]
        # 新しいPOSCARファイルに書き込む
        with open(output_file, 'w') as outfile:
            outfile.writelines(lines)
    
    
    # 新しいPOSCARファイルに書き込んでいく
    def write_species2poscar():
        with open(output_file, 'a') as file:
            # すでに存在するテキストファイルに元素種を追記
            file.write(return_species(df) + '\n')
            # 元素種まで書かれたファイルにDirectという文字をを追記
            file.write('Direct\n' )
            # 直交座標を追記
            file.write(df2str(df))

            
    # 関数をcall
    df2str(df)
    wirte_header2poscar()
    write_species2poscar()
    
    print(f"{output_file} にクラスタ化後の内容が書き込まれました。")

In [252]:
df2poscar()

gen_data/POSCAR にクラスタ化後の内容が書き込まれました。

In [253]:
#### 編集後のposcarファイルをASEで可視化

In [257]:
from ase.io import read, write

output_file="gen_data/POSCAR"
# POSCARファイルの読み込み
atoms = read(output_file)

# POSCARファイルの描画
from ase.visualize import view, ngl
ngl.view_ngl(atoms)

HBox(children=(NGLWidget(), VBox(children=(Dropdown(description='Show', options=('All', 'Sr', 'C'), value='All…

In [258]:
from ase.io import read, write
# POSCARファイルの読み込み
atoms = read('POSCAR')

# POSCARファイルの描画
from ase.visualize import view, ngl
ngl.view_ngl(atoms)

HBox(children=(NGLWidget(), VBox(children=(Dropdown(description='Show', options=('All', 'Sr', 'C', 'O'), value…

### 編集後のPOSCARファイルをVESTAで可視化

In [38]:
from my_package import visualize
POSCAR = './gen_data//POSCAR'
visualize.vesta(POSCAR)

(VESTA-gui:20381): Gtk-WARNING **: 18:41:12.797: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-WARNING **: 18:41:12.797: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-WARNING **: 18:41:12.797: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-WARNING **: 18:41:12.797: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-CRITICAL **: 18:41:12.799: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(VESTA-gui:20381): Gtk-WARNING **: 18:41:12.977: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-WARNING **: 18:41:12.977: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-CRITICAL **: 18:41:12.977: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(VESTA-gui:20381): Gtk-WARNING **: 18:41:13.295: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-WARNING **: 18:41:13.296: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-WARNING **: 18:41:13.296: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-WARNING **: 18:41:13.296: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-CRITICAL **: 18:41:13.296: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(VESTA-gui:20381): Gtk-WARNING **: 18:41:13.459: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-WARNING **: 18:41:13.460: Negative content width -2 (allocation 32, extents 17x17) while allocating gadget (node button, owner GtkButton)

(VESTA-gui:20381): Gtk-CRITICAL **: 18:41:13.460: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

type=0 format=0 nitems=0 atom=276 252
workspace= 0 : -1, x=8, y=64; Screen_W=1504